### ISSUE TITLE
pyflakes>=2.1 compatibility

### ISSUE THREAD

**Issue by rooterkyberian** [nephila/djangocms-helper#111]
is there any reason for preventing `djangocms-helper` installation with newer `pyflakes`?

**Comment by s-weigand** [comment]
I have the problem that `djangocms-helper` breaks my `flake8` tests, because it downgrades `pyflakes`.
To find the culprit I had to run [`johnnydep`](https://github.com/wimglenn/johnnydep) on all installed packages (`pip freeze`) in my virtual env.

**Comment by yakky** [comment]
unfortunately we had to pin `pyflakes` as we use the django-cms provided checks which currently does not support `pyflakes` 2.1
We are monitoring the changes on django CMS and we will evaluate in the next days how to proceed in this regard
One option is to move pyflake to optional dependency to avoid the situation reported by @s-weigand

**Comment by yakky** [comment]
I will remove hard dependency on `pyflakes`` with #117
