### ISSUE TITLE
Incorrect TEMPLATE_CONTEXT_PROCESSORS on Django1.8 

### ISSUE THREAD

**Issue by narayanaditya95** [nephila/djangocms-helper#37]
On Django==1.8 + djangoCMS 3.1.1+, django.conf.settings.TEMPLATES['context_processors'] returns a tuple with template processors that correspond to previous versions of django. For eg: ```django.core.context_processors.request``` instead of ```django.template.context_processors.request```.  
How do we maintain compatibility over different django versions.
Should we perform a string replace of ```django.core``` to ```django.template``` [here](https://github.com/nephila/djangocms-helper/blob/develop/djangocms_helper/utils.py#L273).
```python
        default_settings['TEMPLATES'] = [
            {
                'NAME': 'django',
                'BACKEND': 'django.template.backends.django.DjangoTemplates',
                'APP_DIRS': True,
                'OPTIONS': {
                    'context_processors': [
                        template_processor.replace('django.core', 'django.template')
                        for template_processor in default_settings.pop('TEMPLATE_CONTEXT_PROCESSORS')
                    ]
                }
            }
        ]
```

Also, django.conf.settings.TEMPLATE_CONTEXT_PROCESSORS returns a tuple with no CMS or sekizai context processors included with the same incorrect context processors as noted above.

**Comment by yakky** [comment]
Develop branch should be compatible with Django 1.8
We're completing the test and it's due to release shortly

Il 03 luglio 2015 23:29:25 CEST, Aditya Narayan <notifications@github.com> ha scritto:
>On Django==1.8 + djangoCMS 3.1.x,
>django.conf.settings.TEMPLATES['context_processors'] returns a tuple
>with template processors that correspond to previous versions of
>django. For eg: ```django.core.context_processors.request``` instead of
>```django.template.context_processors.request```.  
>How do we maintain compatibility over different django versions.
>Should we perform a string replace of ```django.core``` to
>```django.template```
>[here](https://github.com/nephila/djangocms-helper/blob/develop/djangocms_helper/utils.py#L273).
>```python
>        default_settings['TEMPLATES'] = [
>            {
>                'NAME': 'django',
>          'BACKEND': 'django.template.backends.django.DjangoTemplates',
>                'APP_DIRS': True,
>                'OPTIONS': {
>                    'context_processors': [
>           template_processor.replace('django.core', 'django.template')
>for template_processor in
>default_settings.pop('TEMPLATE_CONTEXT_PROCESSORS')
>                    ]
>                }
>            }
>        ]
>```
>
>Also, django.conf.settings.TEMPLATE_CONTEXT_PROCESSORS returns a tuple
>with no CMS or sekizai context processors included with the same
>incorrect context processors as noted above.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/nephila/djangocms-helper/issues/37

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by narayanaditya95** [comment]
This issue is encountered with the develop branch too.
I am waiting for the release.
Thanks.

**Comment by yakky** [comment]
@narayanaditya95 Please have a look at above PR
The CMS / sekizai template context processors are included only when running helper in "cms mode" (http://djangocms-helper.readthedocs.org/en/develop/settings.html#cms-option )

**Comment by narayanaditya95** [comment]
LGTM!
Thanks for the fix.
Closing the issue
