### ISSUE TITLE
invoking the server command with --boilerplate option doesn't configures boilerplates

### ISSUE THREAD

**Issue by cyberstar** [nephila/djangocms-helper#48]
Example of a failure https://travis-ci.org/aldryn/aldryn-newsblog/jobs/77465895#L733
the configuration of that particular test https://github.com/aldryn/aldryn-boilerplates/pull/14/files#diff-2b5bde3dd5ae5bc227010549100ba6a8R27

The issue is related to the fact that django runserver command spwans a new process/thread which gets non unicoded arguments in sys.argv.
Also if some of the arguments was passed twice (or was duplicated because of that spawn) docopt wasn't able to map arguments correctly.

**Comment by yakky** [comment]
Fixed by #49
