### ISSUE TITLE
Replace mock package with unittest.mock

### ISSUE THREAD

**Issue by Chronial** [nephila/djangocms-helper#77]
From what I can see, this package does not support any version of python that does not come with `mock` in it's standardlib. Is there any reason not use that?

My main problem is that this lists `mock` as a requirement, which combined with https://github.com/pytest-dev/pytest-mock/pull/54 now messes with my tests :).

**Comment by yakky** [comment]
@Chronial isn't mock in stdlib only for python 3.3+ and up?

**Comment by Chronial** [comment]
Oh, sorry – I must be doing to much python3 :). I for some reason thought it was also part of 2.7, but it is in fact not.

Would it be possible to only require `mock` on python2?

**Comment by yakky** [comment]
@Chronial choiould you check if  #77 fixes the issue for you?

**Comment by Chronial** [comment]
Yes, that looks great, thx :).

**Comment by Chronial** [comment]
@yakky It looks like this doesn't actually work, because you uploaded a py2+py3 wheel to pypi that states that it requires `mock`. The easiest solution to this would probably be to just not provide a wheel.

**Comment by yakky** [comment]
@Chronial my bad, an error in setup.py, fixed in #82
0.9.7 wheel will fix that
