### ISSUE TITLE
create_filer_image_object() bug

### ISSUE THREAD

**Issue by wfehr** [nephila/djangocms-helper#87]
I am using djangocms-helper for running tests in my project and it works very well.
The only problem is, that I have to set 'FILE_UPLOAD_TEMP_DIR' to '/tmp' (or '/tmp/') in the settings.py or the additional helper-settings. The django-doc itself says, that if FILE_UPLOAD_TEMP_DIR is set to 'None' (which is the default), it takes the default temp folder of the system (/tmp on *nix).
If you dont override this value, you get an error from the BaseTestCase in base_test.py. There, the 'create_filer_image_object()' looks at the FILE_UPLOAD_TEMP_DIR from django.conf.settings and joins it with an image_name.
If it is set to 'None', I get the following error:

>     Traceback (most recent call last):
>       File "/usr/local/lib/python3.6/site-packages/djangocms_helper/base_test.py", line 435, in create_filer_image_object
>         file_obj = self.create_django_image_object()
>       File "/usr/local/lib/python3.6/site-packages/djangocms_helper/base_test.py", line 415, in create_django_image_object
>         self.filename = os.path.join(settings.FILE_UPLOAD_TEMP_DIR, self.image_name)
>       File "/usr/local/lib/python3.6/posixpath.py", line 78, in join
>         a = os.fspath(a)
>     TypeError: expected str, bytes or os.PathLike object, not NoneType

In my opinion, the method behaves different than django does itself. It would be really great if you can find a good solution for this problem.

**Comment by yakky** [comment]
@wfehr could you check if ``hotfix/temp_dir`` fixes the issue? Just doing ``pip install https://github.com/nephila/djangocms-helper/archive/hotfix/temp_dir.zip`` should work

**Comment by wfehr** [comment]
@yakky yes, it works fine after installing that hotfix. Ran the tests before and after installing it and without the overriding in the settings.

**Comment by yakky** [comment]
Thanks, merging it. I should be able to release a fixed version shortly

**Comment by yakky** [comment]
Fixed by #90
